const worldPhotos = [
  {
    "key": "performer",
    "title": "Priti Menon",
    "file": "Priti_Menon.jpeg",
    "img": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Priti_Menon.jpeg",
    "author": "Niyazsky",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "position": "50% 40%",
    "alt": "真人持麥克風演唱",
    "source": "https://commons.wikimedia.org/wiki/File:Priti_Menon.jpeg",
    "checked": "2026-09-12"
  },
  {
    "key": "explorer",
    "title": "Tourists shops in the Ancient Village of Hoi An in 2015",
    "file": "Tourists_shops_in_the_Ancient_Village_of_Hoi_An_in_2015.jpg",
    "author": "Vuong Tri Binh",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "position": "68% 50%",
    "alt": "旅人走過會安古城的燈籠與街道",
    "source": "https://commons.wikimedia.org/wiki/File:Tourists_shops_in_the_Ancient_Village_of_Hoi_An_in_2015.jpg",
    "checked": "2026-09-12"
  },
  {
    "key": "adventurer",
    "title": "1993-03-21 Tandemsprong Yolanda Lippens parachutespringen vrije val",
    "file": "1993-03-21_Tandemsprong_Yolanda_Lippens_parachutespringen_vrije_val.jpg",
    "author": "Yolanl",
    "authorUrl": "https://www.yory.nl/",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "position": "50% 45%",
    "alt": "兩人高空雙人跳傘",
    "source": "https://commons.wikimedia.org/wiki/File:1993-03-21_Tandemsprong_Yolanda_Lippens_parachutespringen_vrije_val.jpg",
    "checked": "2026-09-12"
  },
  {
    "key": "creator",
    "title": "Alberto Rey working on a painting for Aesthetics of Death",
    "file": "Alberto_Rey_working_on_a_painting_for_Aesthetics_of_Death.jpg",
    "img": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Alberto_Rey_working_on_a_painting_for_Aesthetics_of_Death.jpg/960px-Alberto_Rey_working_on_a_painting_for_Aesthetics_of_Death.jpg",
    "author": "Alberto Rey",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "position": "50% 40%",
    "alt": "畫家在工作室繪畫",
    "source": "https://commons.wikimedia.org/wiki/File:Alberto_Rey_working_on_a_painting_for_Aesthetics_of_Death.jpg",
    "checked": "2026-09-12"
  },
  {
    "key": "luxury",
    "title": "Good food, beer, wine and sake",
    "file": "Good_food,_beer,_wine_and_sake_(6453643351).jpg",
    "author": "Maarten Heerlien",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "position": "28% 55%",
    "alt": "朋友在日式餐桌共享美食",
    "source": "https://commons.wikimedia.org/wiki/File:Good_food%2C_beer%2C_wine_and_sake_(6453643351).jpg",
    "checked": "2026-09-12"
  },
  {
    "key": "transformer",
    "title": "Personal training military press with dumbbells",
    "file": "Personal_training_military_press_with_dumbbells.jpg",
    "img": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Personal_training_military_press_with_dumbbells.jpg/960px-Personal_training_military_press_with_dumbbells.jpg",
    "author": "PTPioneer",
    "authorUrl": "https://www.ptpioneer.com/",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "position": "50% 40%",
    "alt": "教練指導學員使用啞鈴運動",
    "source": "https://commons.wikimedia.org/wiki/File:Personal_training_military_press_with_dumbbells.jpg",
    "checked": "2026-09-12"
  },
  {
    "key": "entrepreneur",
    "title": "Team Eshopbox",
    "file": "Team_Eshopbox.jpg",
    "author": "Eshopbox",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "position": "50% 35%",
    "alt": "團隊在會議室交流簡報",
    "source": "https://commons.wikimedia.org/wiki/File:Team_Eshopbox.jpg",
    "checked": "2026-09-12"
  },
  {
    "key": "soul",
    "title": "Outdoor yoga",
    "file": "Outdoor_yoga.jpg",
    "img": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Outdoor_yoga.jpg/960px-Outdoor_yoga.jpg",
    "author": "Tz drunk poet",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "position": "50% 50%",
    "alt": "戶外瑜伽練習",
    "source": "https://commons.wikimedia.org/wiki/File:Outdoor_yoga.jpg",
    "checked": "2026-09-12"
  }
];
